// 若谷识字 · 二年级上册词拼音（带声调）
// 生成：tools/build_g2_pinyin.py（pypinyin 初稿）→ 人工校对多音字与轻声（2026-09）
// 说明：直接并入 RUOGU_PINYIN；风格与一年级一致（一不变调、轻声词标轻声）
window.RUOGU_PINYIN = Object.assign(window.RUOGU_PINYIN || {}, {
  "蝌蚪": "kē dǒu",
  "脑筋": "nǎo jīn",
  "口袋": "kǒu dai",
  "灰色": "huī sè",
  "甩开": "shuǎi kāi",
  "生活": "shēng huó",
  "大腿": "dà tuǐ",
  "教课": "jiāo kè",
  "欢迎": "huān yíng",
  "嘴巴": "zuǐ ba",
  "乌龟": "wū guī",
  "披上": "pī shàng",
  "蹲下": "dūn xià",
  "肚子": "dù zi",
  "打鼓": "dǎ gǔ",
  "两条": "liǎng tiáo",
  "哪里": "nǎ li",
  "宽广": "kuān guǎng",
  "那个": "nà ge",
  "长短": "cháng duǎn",
  "孩子": "hái zi",
  "成长": "chéng zhǎng",
  "汽油": "qì yóu",
  "越过": "yuè guò",
  "温暖": "wēn nuǎn",
  "水滴": "shuǐ dī",
  "奔跑": "bēn pǎo",
  "海洋": "hǎi yáng",
  "发现": "fā xiàn",
  "坏人": "huài rén",
  "没有": "méi yǒu",
  "村庄": "cūn zhuāng",
  "庄稼": "zhuāng jia",
  "房屋": "fáng wū",
  "带领": "dài lǐng",
  "火灾": "huǒ zāi",
  "种花": "zhòng huā",
  "水管": "shuǐ guǎn",
  "升起": "shēng qǐ",
  "连线": "lián xiàn",
  "也许": "yě xǔ",
  "作为": "zuò wéi",
  "办法": "bàn fǎ",
  "植树": "zhí shù",
  "如果": "rú guǒ",
  "因为": "yīn wèi",
  "脚步": "jiǎo bù",
  "旅行": "lǚ xíng",
  "准备": "zhǔn bèi",
  "送别": "sòng bié",
  "挂念": "guà niàn",
  "挺立": "tǐng lì",
  "炸开": "zhà kāi",
  "离开": "lí kāi",
  "粗细": "cū xì",
  "得到": "dé dào",
  "大雪纷飞": "dà xuě fēn fēi",
  "已经": "yǐ jīng",
  "告别": "gào bié",
  "轻声": "qīng shēng",
  "出发": "chū fā",
  "大胆": "dà dǎn",
  "肚皮": "dù pí",
  "知识": "zhī shi",
  "晴朗": "qíng lǎng",
  "雾霾": "wù mái",
  "阴转晴": "yīn zhuǎn qíng",
  "闪电": "shǎn diàn",
  "暴风": "bào fēng",
  "雷阵雨": "léi zhèn yǔ",
  "冰雹": "bīng báo",
  "霜冻": "shuāng dòng",
  "雨夹雪": "yǔ jiā xuě",
  "转头": "zhuǎn tóu",
  "发夹": "fà jiā",
  "帆船": "fān chuán",
  "港湾": "gǎng wān",
  "鱼塘": "yú táng",
  "稻田": "dào tián",
  "一行": "yī háng",
  "垂柳": "chuí liǔ",
  "花园": "huā yuán",
  "小溪": "xiǎo xī",
  "丛林": "cóng lín",
  "翠竹": "cuì zhú",
  "一群": "yī qún",
  "队列": "duì liè",
  "铜号": "tóng hào",
  "到处": "dào chù",
  "一块田地": "yī kuài tián dì",
  "一座": "yī zuò",
  "座位": "zuò wèi",
  "一群飞鸟": "yī qún fēi niǎo",
  "红领巾": "hóng lǐng jīn",
  "欢笑": "huān xiào",
  "榕树": "róng shù",
  "强壮": "qiáng zhuàng",
  "梧桐": "wú tóng",
  "手掌": "shǒu zhǎng",
  "枫树": "fēng shù",
  "松柏": "sōng bǎi",
  "桦树": "huà shù",
  "守护": "shǒu hù",
  "银杏": "yín xìng",
  "水杉": "shuǐ shān",
  "化石": "huà shí",
  "金桂": "jīn guì",
  "杨树": "yáng shù",
  "树叶": "shù yè",
  "树之歌": "shù zhī gē",
  "开花": "kāi huā",
  "世界": "shì jiè",
  "孔雀": "kǒng què",
  "锦鸡": "jǐn jī",
  "雄鹰": "xióng yīng",
  "飞翔": "fēi xiáng",
  "雁群": "yàn qún",
  "深处": "shēn chù",
  "猛虎": "měng hǔ",
  "百灵": "bǎi líng",
  "唱不休": "chàng bù xiū",
  "熊猫": "xióng māo",
  "拍手": "pāi shǒu",
  "云彩": "yún cai",
  "休息": "xiū xi",
  "朋友": "péng you",
  "保护": "bǎo hù",
  "春季": "chūn jì",
  "蝴蝶": "hú dié",
  "麦苗": "mài miáo",
  "嫩叶": "nèn yè",
  "肥美": "féi měi",
  "农事": "nóng shì",
  "勤耕作": "qín gēng zuò",
  "归来": "guī lái",
  "戴月光": "dài yuè guāng",
  "场院": "cháng yuàn",
  "谷粒": "gǔ lì",
  "虽然": "suī rán",
  "辛苦": "xīn kǔ",
  "制作": "zhì zuò",
  "四季": "sì jì",
  "事情": "shì qing",
  "谷子": "gǔ zi",
  "身体": "shēn tǐ",
  "初心": "chū xīn",
  "一年": "yī nián",
  "美丑": "měi chǒu",
  "诚实": "chéng shí",
  "彩虹": "cǎi hóng",
  "美丽": "měi lì",
  "浇花": "jiāo huā",
  "提着水壶": "tí zhe shuǐ hú",
  "洒水": "sǎ shuǐ",
  "挑水": "tiāo shuǐ",
  "浇田": "jiāo tián",
  "拿着一面镜子": "ná zhe yī miàn jìng zi",
  "梳头": "shū tóu",
  "系鞋带": "jì xié dài",
  "秋千荡来荡去": "qiū qiān dàng lái dàng qù",
  "裙子": "qún zi",
  "提着": "tí zhe",
  "圆的": "yuán de",
  "哥哥": "gē ge",
  "秋千": "qiū qiān",
  "挂在": "guà zài",
  "好吗": "hǎo ma",
  "好啊": "hǎo a",
  "外婆": "wài pó",
  "小时候": "xiǎo shí hou",
  "乐趣": "lè qù",
  "舅舅": "jiù jiu",
  "或者": "huò zhě",
  "留下": "liú xià",
  "喂山雀": "wèi shān què",
  "蹦来跳去": "bèng lái tiào qù",
  "逃跑": "táo pǎo",
  "唱支小曲": "chàng zhī xiǎo qǔ",
  "姹紫嫣红": "chà zǐ yān hóng",
  "衣服": "yī fu",
  "香气扑鼻": "xiāng qì pū bí",
  "真有趣": "zhēn yǒu qù",
  "宝贝": "bǎo bèi",
  "玩的": "wán de",
  "干活": "gàn huó",
  "一些": "yī xiē",
  "总要": "zǒng yào",
  "给我": "gěi wǒ",
  "告诉": "gào su",
  "曲子": "qǔ zi",
  "名字": "míng zi",
  "香气": "xiāng qì",
  "珍珠": "zhēn zhū",
  "撒落在地": "sǎ luò zài dì",
  "碧玉盘": "bì yù pán",
  "靠着": "kào zhe",
  "仰起头": "yǎng qǐ tóu",
  "几百颗星星": "jǐ bǎi kē xīng xing",
  "乱动": "luàn dòng",
  "中间": "zhōng jiān",
  "隔得很远": "gé dé hěn yuǎn",
  "看得很仔细": "kàn dé hěn zǐ xì",
  "距离不变": "jù lí bù biàn",
  "祖先": "zǔ xiān",
  "一把勺子": "yī bǎ sháo zi",
  "绕着北极星转": "rào zhe běi jí xīng zhuàn",
  "清楚": "qīng chu",
  "果然": "guǒ rán",
  "汉朝": "hàn cháo",
  "刻苦钻研": "kè kǔ zuān yán",
  "著名": "zhù míng",
  "数星星": "shǔ xīng xing",
  "晚上": "wǎn shàng",
  "爷爷": "yé ye",
  "奶奶": "nǎi nai",
  "您看": "nín kàn",
  "很仔细": "hěn zǐ xì",
  "不变": "bù biàn",
  "勺子": "sháo zi",
  "张开": "zhāng kāi",
  "汉语": "hàn yǔ",
  "弹钢琴": "tán gāng qín",
  "练舞蹈": "liàn wǔ dǎo",
  "唱京戏": "chàng jīng xì",
  "画图画": "huà tú huà",
  "捏泥人": "niē ní rén",
  "下围棋": "xià wéi qí",
  "荡秋千": "dàng qiū qiān",
  "滚铁环": "gǔn tiě huán",
  "滑滑梯": "huá huá tī",
  "含苞欲放": "hán bāo yù fàng",
  "百花争艳": "bǎi huā zhēng yàn",
  "花红柳绿": "huā hóng liǔ lǜ",
  "春色满园": "chūn sè mǎn yuán",
  "图画": "tú huà",
  "泥人": "ní rén",
  "铁环": "tiě huán",
  "登山": "dēng shān",
  "唐诗": "táng shī",
  "依然": "yī rán",
  "依依不舍": "yī yī bù shě",
  "尽头": "jìn tóu",
  "食欲": "shí yù",
  "欲言又止": "yù yán yòu zhǐ",
  "穷尽": "qióng jìn",
  "山穷水尽": "shān qióng shuǐ jìn",
  "高层": "gāo céng",
  "瀑布": "pù bù",
  "香炉": "xiāng lú",
  "紫气东来": "zǐ qì dōng lái",
  "烟云": "yān yún",
  "烟消云散": "yān xiāo yún sàn",
  "遥远": "yáo yuǎn",
  "山川": "shān chuān",
  "名山大川": "míng shān dà chuān",
  "层林叠翠": "céng lín dié cuì",
  "依照": "yī zhào",
  "尽力": "jìn lì",
  "无穷": "wú qióng",
  "光照": "guāng zhào",
  "分层": "fēn céng",
  "烟花": "yān huā",
  "正直": "zhèng zhí",
  "银河": "yín hé",
  "中外闻名": "zhōng wài wén míng",
  "风景区": "fēng jǐng qū",
  "安徽省": "ān huī shěng",
  "秀丽神奇": "xiù lì shén qí",
  "神仙": "shén xiān",
  "石盘": "shí pán",
  "指路": "zhǐ lù",
  "巨石": "jù shí",
  "伸手": "shēn shǒu",
  "天都": "tiān dū",
  "著作": "zhù zuò",
  "抢球": "qiǎng qiú",
  "形状": "xíng zhuàng",
  "岩石": "yán shí",
  "岩洞": "yán dòng",
  "仙人": "xiān rén",
  "山顶": "shān dǐng",
  "天狗": "tiān gǒu",
  "闪开": "shǎn kāi",
  "让位": "ràng wèi",
  "潭水": "tán shuǐ",
  "树木茂盛": "shù mù mào shèng",
  "群山环绕": "qún shān huán rào",
  "名胜古迹": "míng shèng gǔ jì",
  "美不胜收": "měi bù shèng shōu",
  "山清水秀": "shān qīng shuǐ xiù",
  "蒙蒙细雨": "méng méng xì yǔ",
  "点点灯光": "diǎn diǎn dēng guāng",
  "中央": "zhōng yāng",
  "海岛": "hǎi dǎo",
  "隐约": "yǐn yuē",
  "倒映": "dào yìng",
  "整个": "zhěng gè",
  "童话": "tóng huà",
  "吸引": "xī yǐn",
  "游客": "yóu kè",
  "山区": "shān qū",
  "湖面": "hú miàn",
  "名胜": "míng shèng",
  "弯月": "wān yuè",
  "现在": "xiàn zài",
  "就是": "jiù shì",
  "中外": "zhōng wài",
  "葡萄沟": "pú tao gōu",
  "山坡": "shān pō",
  "茂密": "mào mì",
  "枝叶": "zhī yè",
  "清绿": "qīng lǜ",
  "热情好客": "rè qíng hào kè",
  "家族": "jiā zú",
  "吃个够": "chī gè gòu",
  "秋收": "qiū shōu",
  "城市": "chéng shì",
  "钉着": "dìng zhe",
  "颜色": "yán sè",
  "味道": "wèi dào",
  "葡萄干": "pú tao gān",
  "水分": "shuǐ fèn",
  "月份": "yuè fèn",
  "好客": "hào kè",
  "小孔": "xiǎo kǒng",
  "五光十色": "wǔ guāng shí sè",
  "订正": "dìng zhèng",
  "效果": "xiào guǒ",
  "丰收": "fēng shōu",
  "昌盛": "chāng shèng",
  "支付": "zhī fù",
  "卧铺": "wò pù",
  "改签": "gǎi qiān",
  "退票": "tuì piào",
  "更改": "gēng gǎi",
  "二维码": "èr wéi mǎ",
  "口号": "kǒu hào",
  "丰年": "fēng nián",
  "观看": "guān kàn",
  "井沿": "jǐng yán",
  "口渴": "kǒu kě",
  "说话": "shuō huà",
  "弄好": "nòng hǎo",
  "对错": "duì cuò",
  "边际": "biān jì",
  "拾起": "shí qǐ",
  "相信": "xiāng xìn",
  "走呀": "zǒu ya",
  "回答": "huí dá",
  "抬头": "tái tóu",
  "不能": "bù néng",
  "号叫": "háo jiào",
  "应当": "yīng dāng",
  "寻找": "xún zhǎo",
  "枯草": "kū cǎo",
  "退却": "tuì què",
  "劝说": "quàn shuō",
  "刮风": "guā fēng",
  "生死": "shēng sǐ",
  "将来": "jiāng lái",
  "而且": "ér qiě",
  "狂风": "kuáng fēng",
  "冷风": "lěng fēng",
  "重复": "chóng fù",
  "复习": "fù xí",
  "呼吸": "hū xī",
  "阵阵秋风": "zhèn zhèn qiū fēng",
  "做像": "zuò xiàng",
  "冰冻": "bīng dòng",
  "第一": "dì yī",
  "冰冷": "bīng lěng",
  "天亮": "tiān liàng",
  "葫芦": "hú lú",
  "芦花": "lú huā",
  "感谢": "gǎn xiè",
  "比赛": "bǐ sài",
  "奇怪": "qí guài",
  "快慢": "kuài màn",
  "种子": "zhǒng zi",
  "种树": "zhòng shù",
  "一棵": "yī kē",
  "可以": "kě yǐ",
  "几次": "jǐ cì",
  "心想": "xīn xiǎng",
  "邻居": "lín jū",
  "好吧": "hǎo ba",
  "轿车": "jiào chē",
  "救护车": "jiù hù chē",
  "摩托车": "mó tuō chē",
  "消防车": "xiāo fáng chē",
  "渔船": "yú chuán",
  "货船": "huò chuán",
  "轮船": "lún chuán",
  "科学考察船": "kē xué kǎo chá chuán",
  "货车": "huò chē",
  "科目": "kē mù",
  "高楼": "gāo lóu",
  "艰苦": "jiān kǔ",
  "斗争": "dòu zhēng",
  "年代": "nián dài",
  "来临": "lái lín",
  "临时": "lín shí",
  "腊月": "là yuè",
  "军队": "jūn duì",
  "薄被": "báo bèi",
  "文章": "wén zhāng",
  "握手": "wò shǒu",
  "凝视": "níng shì",
  "觉得": "jué de",
  "味觉": "wèi jué",
  "油灯": "yóu dēng",
  "加油": "jiā yóu",
  "光辉": "guāng huī",
  "革命": "gé mìng",
  "生命": "shēng mìng",
  "胜利": "shèng lì",
  "明亮": "míng liàng",
  "中国": "zhōng guó",
  "道路": "dào lù",
  "星星之火": "xīng xīng zhī huǒ",
  "上楼": "shàng lóu",
  "穿衣": "chuān yī",
  "电视": "diàn shì",
  "朱德": "zhū dé",
  "德行": "dé xíng",
  "扁担": "biǎn dan",
  "扁豆": "biǎn dòu",
  "分担": "fēn dān",
  "同志": "tóng zhì",
  "队伍": "duì wu",
  "敌人": "dí rén",
  "敌对": "dí duì",
  "根据": "gēn jù",
  "树根": "shù gēn",
  "收据": "shōu jù",
  "抽出": "chōu chū",
  "抽空": "chōu kòng",
  "陡坡": "dǒu pō",
  "草鞋": "cǎo xié",
  "头疼": "tóu téng",
  "敬爱": "jìng ài",
  "山高路陡": "shān gāo lù dǒu",
  "红军": "hóng jūn",
  "生产": "shēng chǎn",
  "常常": "cháng cháng",
  "来回": "lái huí",
  "非常": "fēi cháng",
  "战士": "zhàn shì",
  "一块儿": "yī kuài ér",
  "军人": "jūn rén",
  "每天": "měi tiān",
  "穿戴": "chuān dài",
  "泼水": "pō shuǐ",
  "活泼": "huó pō",
  "民族": "mín zú",
  "度过": "dù guò",
  "特别": "tè bié",
  "四周": "sì zhōu",
  "恩情": "ēn qíng",
  "敲门": "qiāo mén",
  "铺路": "pū lù",
  "龙船": "lóng chuán",
  "手串": "shǒu chuàn",
  "笑容": "xiào róng",
  "踩水": "cǎi shuǐ",
  "开始": "kāi shǐ",
  "盛水": "chéng shuǐ",
  "木碗": "mù wǎn",
  "祝福": "zhù fú",
  "长寿": "cháng shòu",
  "寿命": "shòu mìng",
  "难忘": "nán wàng",
  "火红": "huǒ hóng",
  "人民": "rén mín",
  "总理": "zǒng lǐ",
  "人们": "rén men",
  "为了": "wèi le",
  "人群": "rén qún",
  "欢乐": "huān lè",
  "开心": "kāi xīn",
  "一串": "yī chuàn",
  "长裤": "cháng kù",
  "命令": "mìng lìng",
  "四面八方": "sì miàn bā fāng",
  "姓刘": "xìng liú",
  "兰花": "lán huā",
  "反派": "fǎn pài",
  "气派": "qì pài",
  "由于": "yóu yú",
  "出卖": "chū mài",
  "人员": "rén yuán",
  "被捕": "bèi bǔ",
  "捕捉": "bǔ zhuō",
  "买卖": "mǎi mài",
  "似的": "shì de",
  "踏青": "tà qīng",
  "烈士": "liè shì",
  "光荣": "guāng róng",
  "年岁": "nián suì",
  "题目": "tí mù",
  "年轻": "nián qīng",
  "消息": "xiāo xi",
  "正反": "zhèng fǎn",
  "山村": "shān cūn",
  "被告": "bèi gào",
  "声音": "shēng yīn",
  "岁月": "suì yuè",
  "一点儿": "yī diǎn ér",
  "共产党员": "gòng chǎn dǎng yuán",
  "锋利": "fēng lì",
  "蜜蜂": "mì fēng",
  "山峰": "shān fēng",
  "火爆": "huǒ bào",
  "抄写": "chāo xiě",
  "炒菜": "chǎo cài",
  "幕布": "mù bù",
  "墓地": "mù dì",
  "爱慕": "ài mù",
  "炒面": "chǎo miàn",
  "绝对": "jué duì",
  "小径": "xiǎo jìng",
  "踪迹": "zōng jì",
  "消灭": "xiāo miè",
  "孤舟": "gū zhōu",
  "钓鱼": "diào yú",
  "好似": "hǎo sì",
  "穹庐": "qióng lú",
  "笼罩": "lǒng zhào",
  "盖住": "gài zhù",
  "苍茫": "cāng máng",
  "灭绝": "miè jué",
  "舟车": "zhōu chē",
  "龙舟": "lóng zhōu",
  "孤独": "gū dú",
  "阴沉": "yīn chén",
  "田野": "tián yě",
  "低头": "dī tóu",
  "无论": "wú lùn",
  "变暗": "biàn àn",
  "岸边": "àn biān",
  "街道": "jiē dào",
  "桥梁": "qiáo liáng",
  "甚至": "shèn zhì",
  "一切": "yī qiè",
  "躲藏": "duǒ cáng",
  "应该": "yīng gāi",
  "悠闲": "yōu xián",
  "散步": "sàn bù",
  "消失": "xiāo shī",
  "船只": "chuán zhī",
  "小猫": "xiǎo māo",
  "于是": "yú shì",
  "同时": "tóng shí",
  "行人": "xíng rén",
  "堆雪人": "duī xuě rén",
  "玩累了": "wán lèi le",
  "添把柴": "tiān bǎ chái",
  "火烧得旺旺的": "huǒ shāo dé wàng wàng de",
  "闭上眼睛": "bì shàng yǎn jing",
  "哎呀": "āi yā",
  "旁边": "páng biān",
  "冲进": "chōng jìn",
  "哇": "wa",
  "终于": "zhōng yú",
  "混身": "hún shēn",
  "水淋淋": "shuǐ lín lín",
  "晒太阳": "shài tài yáng",
  "主要": "zhǔ yào",
  "伙伴": "huǒ bàn",
  "唱歌": "chàng gē",
  "吃得好": "chī dé hǎo",
  "关闭": "guān bì",
  "连忙": "lián máng",
  "谁的": "shéi de",
  "水汽": "shuǐ qì",
  "空地": "kòng dì",
  "回家": "huí jiā",
  "云开雾散": "yún kāi wù sàn",
  "微风习习": "wēi fēng xí xí",
  "冰天雪地": "bīng tiān xuě dì",
  "风雨交加": "fēng yǔ jiāo jiā",
  "云雾缭绕": "yún wù liáo rào",
  "寒风呼啸": "hán fēng hū xiào",
  "鹅毛大雪": "é máo dà xuě",
  "电闪雷鸣": "diàn shǎn léi míng",
  "饥饿": "jī è",
  "安宁": "ān níng",
  "车库": "chē kù",
  "称赞": "chēng zàn",
  "刺猬": "cì wei",
  "采果子": "cǎi guǒ zi",
  "板凳": "bǎn dèng",
  "粗糙": "cū cāo",
  "但是": "dàn shì",
  "认真": "rèn zhēn",
  "高兴极了": "gāo xìng jí le",
  "傍晚": "bàng wǎn",
  "苹果": "píng guǒ",
  "一把椅子": "yī bǎ yǐ zi",
  "不好意思": "bù hǎo yì sī",
  "泄气": "xiè qì",
  "一点儿心意": "yī diǎn ér xīn yì",
  "接过": "jiē guò",
  "消除": "xiāo chú",
  "疲劳": "pí láo",
  "拿起": "ná qǐ",
  "仔细": "zǐ xì",
  "送给": "sòng gěi",
  "椅子": "yǐ zi",
  "怎么": "zěn me",
  "拉手": "lā shǒu",
  "收下": "shōu xià",
  "接过来": "jiē guò lái",
  "风筝": "fēng zheng",
  "松鼠": "sōng shǔ",
  "折纸船": "zhé zhǐ chuán",
  "漂流": "piāo liú",
  "扎风筝": "zā fēng zheng",
  "乘着风": "chéng zhe fēng",
  "抓住": "zhuā zhù",
  "风筝线": "fēng zheng xiàn",
  "草莓": "cǎo méi",
  "他们俩": "tā men liǎ",
  "吵架": "chǎo jià",
  "很难过": "hěn nán guò",
  "受不了": "shòu bù liǎo",
  "愿意": "yuàn yì",
  "朝他飞来": "cháo tā fēi lái",
  "取下来": "qǔ xià lái",
  "一张纸": "yī zhāng zhǐ",
  "一条线": "yī tiáo xiàn",
  "一句话": "yī jù huà",
  "哭了": "kū le",
  "迎面撞到": "yíng miàn zhuàng dào",
  "抱怨": "bào yuàn",
  "松软": "sōng ruǎn",
  "呜呜地哭": "wū wū de kū",
  "慈祥": "cí xiáng",
  "力量": "lì liàng",
  "跌跟头": "diē gēn tou",
  "摔倒": "shuāi dǎo",
  "擦眼泪": "cā yǎn lèi",
  "咱们": "zán men",
  "推着": "tuī zhe",
  "驶向前方": "shǐ xiàng qián fāng",
  "坚硬的石头": "jiān yìng de shí tou",
  "冲刷": "chōng shuā",
  "游戏": "yóu xì",
  "可爱": "kě ài",
  "笑呢": "xiào ne",
  "跳下来": "tiào xià lái",
  "一只狼": "yī zhī láng",
  "猩猩": "xīng xing",
  "白鹤": "bái hè",
  "一条蛇": "yī tiáo shé",
  "鸽子": "gē zi",
  "蚕宝宝": "cán bǎo bao",
  "蚯蚓": "qiū yǐn",
  "骆驼": "luò tuo",
  "虾米": "xiā mi",
  "狮子": "shī zi",
  "数数儿": "shǔ shù ér",
  "纸船": "zhǐ chuán",
  "可能": "kě néng",
});
