// 若谷识字 · 整词拼音映射（带声调）
// 用途：游戏认读关「看词选拼音」；为 RUOGU_OCR 每个词提供读音
// 生成：Claude Opus 4.8，多音字按词义定音；状态：待家长抽查
// 结构：window.RUOGU_PINYIN = { "词": "pīn yīn", ... }
window.RUOGU_PINYIN = {
  // ===== 上册 · 第一单元 =====
  "天地":"tiān dì","大人":"dà rén","你的":"nǐ de","我的":"wǒ de","他人":"tā rén",
  "一":"yī","二":"èr","三":"sān","四":"sì","五":"wǔ","上":"shàng","下":"xià",
  "一个":"yī gè","二日":"èr rì","三十":"sān shí","七个":"qī gè","八十":"bā shí","六人":"liù rén",
  "人口":"rén kǒu","耳目":"ěr mù","手足":"shǒu zú","站立":"zhàn lì","坐下":"zuò xià",
  "口水":"kǒu shuǐ","手上":"shǒu shàng",
  "日月":"rì yuè","山川":"shān chuān","水火":"shuǐ huǒ","水田":"shuǐ tián","禾苗":"hé miáo",
  "大火":"dà huǒ","六":"liù","七":"qī","八":"bā","九":"jiǔ","十":"shí",
  // ===== 上册 · 第二单元 =====
  "爸爸":"bà ba","妈妈":"mā ma","大地":"dà dì","马路":"mǎ lù","泥土":"ní tǔ",
  "学校":"xué xiào","班级":"bān jí","姓名":"xìng míng","王子":"wáng zǐ","本子":"běn zi",
  "九个":"jiǔ gè",
  // ===== 上册 · 第三单元 =====
  "哥哥":"gē ge","弟弟":"dì di","画画":"huà huà","荷花":"hé huā",
  "下棋":"xià qí","搭积木":"dā jī mù","打鼓":"dǎ gǔ",
  "字":"zì","词":"cí","句子":"jù zi",
  "擦桌子":"cā zhuō zi","折纸":"zhé zhǐ","读书":"dú shū",
  "小鱼":"xiǎo yú","鸭子":"yā zi","乌鸦":"wū yā","蚂蚁":"mǎ yǐ","下午":"xià wǔ",
  "上午":"shàng wǔ","星期":"xīng qī","语文":"yǔ wén","数学":"shù xué","写字":"xiě zì",
  "一会":"yī huì","小鸡":"xiǎo jī","鱼儿":"yú ér","小河":"xiǎo hé","一座山":"yī zuò shān",
  "一棵树":"yī kē shù","四只鸽子":"sì zhī gē zi","七朵花":"qī duǒ huā",
  "一模一样":"yī mú yī yàng","一心一意":"yī xīn yī yì","独一无二":"dú yī wú èr",
  "三头六臂":"sān tóu liù bì","五颜六色":"wǔ yán liù sè","十全十美":"shí quán shí měi",
  // ===== 上册 · 第四单元 =====
  "白菜":"bái cài","西瓜":"xī guā","水果":"shuǐ guǒ",
  "小桥":"xiǎo qiáo","流水":"liú shuǐ","垂柳":"chuí liǔ","桃花":"táo huā",
  "梅花开":"méi huā kāi","雪花飘":"xuě huā piāo","夜色美":"yè sè měi",
  "蓝天":"lán tiān","白云":"bái yún","草原":"cǎo yuán","森林":"sēn lín",
  "游泳":"yóu yǒng","滑冰":"huá bīng","骑自行车":"qí zì xíng chē","打乒乓球":"dǎ pīng pāng qiú",
  "下去":"xià qù","晚上":"wǎn shàng","明天":"míng tiān","今天":"jīn tiān",
  "上个月":"shàng gè yuè","这个月":"zhè gè yuè","去年":"qù nián","火车":"huǒ chē",
  "马车":"mǎ chē","汽车":"qì chē","车站":"chē zhàn","车厢":"chē xiāng","上车":"shàng chē",
  "坐车":"zuò chē","昨天":"zuó tiān",
  // ===== 上册 · 第五单元 =====
  "秋天":"qiū tiān","天气":"tiān qì","飞了":"fēi le","树叶":"shù yè","黄了":"huáng le",
  "一片":"yī piàn","从来":"cóng lái","去了":"qù le","个子":"gè zi",
  "江南":"jiāng nán","可以":"kě yǐ","采莲":"cǎi lián","游戏":"yóu xì","中间":"zhōng jiān",
  "东西":"dōng xī","南北":"nán běi","可口":"kě kǒu","叶子":"yè zi",
  "好的":"hǎo de","画家":"huà jiā","竹叶":"zhú yè","月牙":"yuè yá","不用":"bù yòng",
  "几步":"jǐ bù","没有":"méi yǒu","参加":"cān jiā","竹子":"zhú zi","小鸟":"xiǎo niǎo","几个":"jǐ gè",
  "说话":"shuō huà","春天":"chūn tiān","青蛙":"qīng wā","夏天":"xià tiān","就是":"jiù shì",
  "冬天":"dōng tiān","走着":"zǒu zhe","顽皮地说":"wán pí de shuō","四十":"sì shí","可是":"kě shì","几天":"jǐ tiān",
  "男女":"nán nǚ","开关":"kāi guān","正反":"zhèng fǎn","先后":"xiān hòu","内外":"nèi wài",
  "青草":"qīng cǎo","莲花":"lián huā","飞鸟":"fēi niǎo","雪人":"xuě rén",
  "女人":"nǚ rén","先生":"xiān sheng",
  // ===== 上册 · 第六单元 =====
  "下雨":"xià yǔ","虫子":"chóng zi","山清水秀":"shān qīng shuǐ xiù","柳绿桃红":"liǔ lǜ táo hóng",
  "对韵歌":"duì yùn gē","雪对风":"xuě duì fēng",
  "大山":"dà shān","山水":"shān shuǐ","木耳":"mù ěr","男子":"nán zǐ","水土":"shuǐ tǔ","大力":"dà lì","小心":"xiǎo xīn",
  "开心":"kāi xīn","金黄":"jīn huáng","关心":"guān xīn","力气":"lì qì","尘土":"chén tǔ",
  "众人":"zhòng rén","双手":"shuāng shǒu","木条":"mù tiáo","草尖":"cǎo jiān",
  "书包":"shū bāo","尺子":"chǐ zi","作业本":"zuò yè běn","铅笔":"qiān bǐ","转笔刀":"zhuàn bǐ dāo",
  "宝贝":"bǎo bèi","多少":"duō shǎo","课本":"kè běn","早上":"zǎo shàng",
  "小刀":"xiǎo dāo","不会":"bù huì","不少":"bù shǎo",
  "升国旗":"shēng guó qí","中国":"zhōng guó","红旗":"hóng qí","我们":"wǒ men","歌声":"gē shēng",
  "起立":"qǐ lì","多么":"duō me","方向":"fāng xiàng","立正":"lì zhèng",
  "中心":"zhōng xīn","五个":"wǔ gè","风雨":"fēng yǔ",
  "老师":"lǎo shī","工厂":"gōng chǎng","工人":"gōng rén","医院":"yī yuàn","医生":"yī shēng",
  "门卫":"mén wèi","你们":"nǐ men","家里":"jiā lǐ","男生":"nán shēng","蓝色":"lán sè",
  "上山":"shàng shān","三年":"sān nián","报纸":"bào zhǐ",
  // ===== 上册 · 第七单元 =====
  "弯弯":"wān wān","两头":"liǎng tóu","不在":"bù zài","里头":"lǐ tou","看见":"kàn jiàn",
  "闪光":"shǎn guāng","月儿":"yuè ér","小船":"xiǎo chuán","少见":"shǎo jiàn",
  "前后":"qián hòu","常常":"cháng cháng","黑狗":"hēi gǒu","左右":"zuǒ yòu","它们":"tā men",
  "好朋友":"hǎo péng you","影子":"yǐng zi",
  "有人":"yǒu rén","和平":"hé píng","做事":"zuò shì","也是":"yě shì","办到":"bàn dào",
  "又是":"yòu shì","才能":"cái néng","两件宝":"liǎng jiàn bǎo","和我":"hé wǒ","才用":"cái yòng",
  "爷爷":"yé ye","奶奶":"nǎi nai","叔叔":"shū shu","姐姐":"jiě jie","妹妹":"mèi mei",
  // ===== 上册 · 第八单元 =====
  "比尾巴":"bǐ wěi ba","谁的":"shuí de","长短":"cháng duǎn","一把伞":"yī bǎ sǎn","兔子":"tù zi",
  "最好":"zuì hǎo","公鸡":"gōng jī","比一比":"bǐ yī bǐ","下巴":"xià ba","长的":"cháng de","公马":"gōng mǎ",
  "喝水":"hē shuǐ","一只":"yī zhī","到处":"dào chù","找水":"zhǎo shuǐ","喝不着":"hē bù zháo",
  "许多":"xǔ duō","石子":"shí zǐ","出来":"chū lái","办法":"bàn fǎ","放进":"fàng jìn","升高":"shēng gāo",
  "不多":"bù duō","办公":"bàn gōng",
  "雨点":"yǔ diǎn","数不清":"shǔ bù qīng","彩色":"cǎi sè","半空":"bàn kōng","问答":"wèn dá",
  "回答":"huí dá","地方":"dì fāng","不久":"bù jiǔ","更红":"gèng hóng","长出":"zhǎng chū",
  "来去":"lái qù","一半":"yī bàn","有水":"yǒu shuǐ",
  "牛羊":"niú yáng","爪子":"zhuǎ zi","一元":"yī yuán","拼音":"pīn yīn","白色":"bái sè","明月":"míng yuè",
  "大风":"dà fēng","小山":"xiǎo shān","果皮":"guǒ pí","树皮":"shù pí","加法":"jiā fǎ",
  "回来":"huí lái","不许":"bù xǔ","四处":"sì chù","白天":"bái tiān",

  // ===== 下册 · 第一单元 =====
  "春风吹":"chūn fēng chuī","夏雨落":"xià yǔ luò","秋霜降":"qiū shuāng jiàng","冬雪飘":"dōng xuě piāo",
  "红花":"hóng huā","游鱼":"yóu yú","池草青":"chí cǎo qīng","山花红":"shān huā hóng",
  "鱼出水":"yú chū shuǐ","鸟入林":"niǎo rù lín","春雨":"chūn yǔ","吹风":"chuī fēng","白花":"bái huā",
  "飞入":"fēi rù","入口":"rù kǒu",
  "姓氏":"xìng shì","什么":"shén me","李子":"lǐ zǐ","张开":"zhāng kāi","古人":"gǔ rén","胡子":"hú zi",
  "语言":"yǔ yán","孙子":"sūn zi","弯弓":"wān gōng","姓吴":"xìng wú","双方":"shuāng fāng","发言":"fā yán",
  "河水":"hé shuǐ","晴天":"qíng tiān","眼睛":"yǎn jīng","保护":"bǎo hù","树苗":"shù miáo","吃饭":"chī fàn",
  "事情":"shì qíng","请问":"qǐng wèn","不让":"bù ràng","青山":"qīng shān","清水":"qīng shuǐ",
  "花生":"huā shēng","情人":"qíng rén",
  "身边":"shēn biān","凉快":"liáng kuài","喜欢":"xǐ huān","时间":"shí jiān","害怕":"hài pà",
  "万里无云":"wàn lǐ wú yún","猜想":"cāi xiǎng","进攻":"jìn gōng","口令":"kǒu lìng","感动":"gǎn dòng",
  "文字":"wén zì","明白":"míng bái","无人":"wú rén","不动":"bù dòng","万里":"wàn lǐ",
  "组词":"zǔ cí","计算":"jì suàn","减法":"jiǎn fǎ","列算式":"liè suàn shì","图形":"tú xíng",
  "卡片":"kǎ piàn","合唱团":"hé chàng tuán","识字":"shí zì","读课文":"dú kè wén","合力":"hé lì","文明":"wén míng",
  // ===== 下册 · 第二单元 =====
  "水井":"shuǐ jǐng","城市":"chéng shì","乡村":"xiāng cūn","毛主席":"máo zhǔ xí","住房":"zhù fáng",
  "乡亲":"xiāng qīn","战士":"zhàn shì","想念":"xiǎng niàn","井口":"jǐng kǒu","主动":"zhǔ dòng",
  "村子":"cūn zi","亲人":"qīn rén","念书":"niàn shū","战友":"zhàn yǒu","井水":"jǐng shuǐ","公主":"gōng zhǔ",
  "长江":"cháng jiāng","东方":"dōng fāng","后来":"hòu lái","卡住":"qiǎ zhù",
  "告诉":"gào su","行走":"xíng zǒu","北京":"běi jīng","一座":"yī zuò","天安门":"tiān ān mén",
  "广场":"guǎng chǎng","非常":"fēi cháng","美丽":"měi lì","弯弯的小路":"wān wān de xiǎo lù",
  "宽宽的公路":"kuān kuān de gōng lù","美丽的天山":"měi lì de tiān shān","洁白的雪莲":"jié bái de xuě lián",
  "雄伟的天安门":"xióng wěi de tiān ān mén","壮观的升旗仪式":"zhuàng guān de shēng qí yí shì","宽广":"kuān guǎng",
  "广告":"guǎng gào",
  "热爱":"rè ài","共产党":"gòng chǎn dǎng","太阳":"tài yáng","阳光":"yáng guāng","怀抱":"huái bào",
  "幸福":"xìng fú","成长":"chéng zhǎng","光明":"guāng míng","产生":"chǎn shēng","公共":"gōng gòng",
  "认一认":"rèn yī rèn","连一连":"lián yī lián","选一选":"xuǎn yī xuǎn","圈一圈":"quān yī quān",
  "涂一涂":"tú yī tú","填一填":"tián yī tián","试一试":"shì yī shì","练一练":"liàn yī liàn",
  "手写":"shǒu xiě","认出":"rèn chū","写生":"xiě shēng",
  // ===== 下册 · 第三单元 =====
  "爱玩":"ài wán","急得直哭":"jí de zhí kū","跟前":"gēn qián","忽然":"hū rán","听见":"tīng jiàn",
  "喊叫":"hǎn jiào","后背":"hòu bèi","快点":"kuài diǎn","自己":"zì jǐ",
  "说明":"shuō míng","让开":"ràng kāi",
  "只有":"zhǐ yǒu","很好":"hěn hǎo","孤单":"gū dān","种树":"zhòng shù","每年":"měi nián","都有":"dōu yǒu",
  "邻居":"lín jū","叫声":"jiào shēng","招呼":"zhāo hu","快乐":"kuài lè","好心":"hǎo xīn","他们":"tā men",
  "叫好":"jiào hǎo","回去":"huí qù",
  "独自":"dú zì","跳绳":"tiào shéng","当然":"dāng rán","还是":"hái shì","静悄悄":"jìng qiāo qiāo",
  "没劲":"méi jìn","羽毛球":"yǔ máo qiú","轮流":"lún liú","玩游戏":"wán yóu xì","踢足球":"tī zú qiú",
  "听音乐":"tīng yīn yuè","看书":"kàn shū","打排球":"dǎ pái qiú","怎么":"zěn me","音乐":"yīn yuè","非得":"fēi děi",
  "当心":"dāng xīn","书本":"shū běn","动画":"dòng huà","白毛":"bái máo","止住":"zhǐ zhù","公斤":"gōng jīn",
  "尺寸":"chǐ cùn","人丁":"rén dīng","千万":"qiān wàn","一旦":"yī dàn","花旦":"huā dàn",
  // ===== 下册 · 第四单元 =====
  "安静":"ān jìng","思想":"sī xiǎng","床头":"chuáng tóu","疑问":"yí wèn","举手":"jǔ shǒu","看望":"kàn wàng",
  "低头":"dī tóu","故乡":"gù xiāng","心思":"xīn sī",
  "胆子":"dǎn zi","不敢":"bù gǎn","勇敢":"yǒng gǎn","讲话":"jiǎng huà","窗外":"chuāng wài","乱跳":"luàn tiào",
  "拉开":"lā kāi","一样":"yī yàng","微笑":"wēi xiào","再见":"zài jiàn","睡觉":"shuì jiào","胆量":"dǎn liàng",
  "大胆":"dà dǎn","勇气":"yǒng qì","勇士":"yǒng shì","样子":"yàng zi","花样":"huā yàng","再三":"zài sān","再次":"zài cì",
  "出色":"chū sè","火把":"huǒ bǎ","讲和":"jiǎng hé","可笑":"kě xiào",
  "端午":"duān wǔ","粽子":"zòng zi","节日":"jié rì","总是":"zǒng shì","煮饭":"zhǔ fàn","盼望":"pàn wàng",
  "糯米":"nuò mǐ","红枣":"hóng zǎo","香甜":"xiāng tián","分给":"fēn gěi","鲜肉":"xiān ròu","了不起":"liǎo bu qǐ",
  "大米":"dà mǐ","分开":"fēn kāi","吃力":"chī lì","羊肉":"yáng ròu",
  "一册书":"yī cè shū","一支铅笔":"yī zhī qiān bǐ","一台电视":"yī tái diàn shì","一部手机":"yī bù shǒu jī",
  "一件上衣":"yī jiàn shàng yī","一条裤子":"yī tiáo kù zi","一床棉被":"yī chuáng mián bèi",
  "手册":"shǒu cè","开支":"kāi zhī","电子":"diàn zǐ","雨衣":"yǔ yī","电动":"diàn dòng",
  // ===== 下册 · 第五单元 =====
  "动物":"dòng wù","捉迷藏":"zhuō mí cáng","造句":"zào jù","运动":"yùn dòng","食物":"shí wù","房子":"fáng zi",
  "蜻蜓展翅":"qīng tíng zhǎn chì","结网":"jié wǎng","蝴蝶飞舞":"hú dié fēi wǔ","蚂蚁搬家":"mǎ yǐ bān jiā",
  "蜘蛛结网":"zhī zhū jié wǎng","粮食":"liáng shi","蚯蚓松土":"qiū yǐn sōng tǔ","蝌蚪游泳":"kē dǒu yóu yǒng",
  "文物":"wén wù","造房子":"zào fáng zi","房产":"fáng chǎn","欢乐":"huān lè","上网":"shàng wǎng",
  "严寒":"yán hán","酷暑":"kù shǔ","温暖":"wēn nuǎn","早晨":"zǎo chén","细雨":"xì yǔ","朝霞":"zhāo xiá",
  "夕阳":"xī yáng","杨树":"yáng shù","鸟语花香":"niǎo yǔ huā xiāng","方圆":"fāng yuán","和风细雨":"hé fēng xì yǔ",
  "对手":"duì shǒu","白雪":"bái xuě","细长":"xì cháng",
  "操场":"cāo chǎng","拔河":"bá hé","拍皮球":"pāi pí qiú","跑步":"pǎo bù","铃声":"líng shēng","身体":"shēn tǐ",
  "丢沙包":"diū shā bāo","真热闹":"zhēn rè nao","打开":"dǎ kāi","皮毛":"pí máo","长跑":"cháng pǎo","沙土":"shā tǔ",
  "之后":"zhī hòu","初中":"chū zhōng","相关":"xiāng guān","远近":"yuǎn jìn","学习":"xué xí","教学":"jiào xué",
  "知道":"zhī dào","专门":"zhuān mén","幼儿园":"yòu ér yuán","玉器":"yù qì","意义":"yì yì","相近":"xiāng jìn",
  "相反":"xiāng fǎn","练习":"liàn xí","道路":"dào lù","专心":"zhuān xīn","正义":"zhèng yì","玉石":"yù shí",
  "泡茶":"pào chá","轻松":"qīng sōng","鞭炮":"biān pào","穿衣":"chuān yī","睡袍":"shuì páo",
  "饱和":"bǎo hé","吃饱":"chī bǎo","抱住":"bào zhù",
  // ===== 下册 · 第六单元 =====
  "首都":"shǒu dū","偷看":"tōu kàn","浮萍":"fú píng","泉水":"quán shuǐ","爱惜":"ài xī","关照":"guān zhào",
  "清泉":"qīng quán","柔和":"róu hé","荷叶":"hé yè","露珠":"lù zhū","尖角":"jiān jiǎo","可惜":"kě xī",
  "照样":"zhào yàng","照片":"zhào piàn","柔美":"róu měi","轻柔":"qīng róu","漂浮":"piāo fú",
  "一首":"yī shǒu","水池":"shuǐ chí","采花":"cǎi huā","尖叫":"jiān jiào","牛角":"niú jiǎo","清早":"qīng zǎo",
  "水珠":"shuǐ zhū","摇篮":"yáo lán","亮晶晶":"liàng jīng jīng","停机坪":"tíng jī píng","展开":"zhǎn kāi",
  "透明":"tòu míng","翅膀":"chì bǎng","花朵":"huā duǒ","飞机":"fēi jī","讲台":"jiǎng tái","合唱":"hé chàng",
  "雨伞":"yǔ sǎn","美好":"měi hǎo",
  "不要":"bù yào","山腰":"shān yāo","阴沉沉":"yīn chén chén","哎呀":"āi ya","连忙":"lián máng",
  "忙着呢":"máng zhe ne","是吗":"shì ma","对面":"duì miàn","没空":"méi kòng","很闷":"hěn mèn","好吧":"hǎo ba",
  "消息":"xiāo xī","这里":"zhè lǐ","鱼头":"yú tóu","后面":"hòu miàn","问好":"wèn hǎo","加入":"jiā rù",
  "浪花":"làng huā","迈步":"mài bù","悄悄":"qiāo qiāo","眼泪":"yǎn lèi","这次":"zhè cì","小虾":"xiǎo xiā",
  "贝壳":"bèi ké","服装":"fú zhuāng","好像":"hǎo xiàng","淘气":"táo qì","娃娃":"wá wa","交给":"jiāo gěi",
  "分贝":"fēn bèi","吹气":"chuī qì",
  "冰棍":"bīng gùn","绿豆汤":"lǜ dòu tāng","凉席":"liáng xí","蚊香":"wén xiāng","花露水":"huā lù shuǐ",
  "蒲扇":"pú shàn","竹椅":"zhú yǐ","萤火虫":"yíng huǒ chóng","牵牛":"qiān niú","织女":"zhī nǚ","北斗星":"běi dǒu xīng",
  "红豆":"hóng dòu","北斗":"běi dǒu","豆角":"dòu jiǎo",
  // ===== 下册 · 第七单元 =====
  "文具":"wén jù","笔盒":"bǐ hé","一些":"yī xiē","从此":"cóng cǐ","仔细":"zǐ xì","检查":"jiǎn chá",
  "所以":"suǒ yǐ","伙伴":"huǒ bàn","新书":"xīn shū","平时":"píng shí","平常":"píng cháng","平地":"píng dì",
  "相伴":"xiāng bàn","新年":"xīn nián","新手":"xīn shǒu","清新":"qīng xīn","平安":"píng ān","做伴":"zuò bàn",
  "毛笔":"máo bǐ","放心":"fàng xīn","放学":"fàng xué",
  "一分钟":"yī fēn zhōng","迟到":"chí dào","背包":"bēi bāo","红灯":"hóng dēng","等于":"děng yú","好啊":"hǎo a",
  "决定":"jué dìng","已经":"yǐ jīng","座位":"zuò wèi","手表":"shǒu biǎo","元旦":"yuán dàn","灯光":"dēng guāng",
  "请坐":"qǐng zuò",
  "老虎":"lǎo hǔ","狗熊":"gǒu xióng","通知":"tōng zhī","注意":"zhù yì","一遍":"yī biàn","因为":"yīn wèi",
  "舌头":"shé tou","道理":"dào lǐ","忘记":"wàng jì","百千":"bǎi qiān","鬼脸":"guǐ liǎn","准时":"zhǔn shí",
  "第一":"dì yī","国王":"guó wáng","都来":"dōu lái","百万":"bǎi wàn","听话":"tīng huà","时光":"shí guāng","点头":"diǎn tóu","竹林":"zhú lín",
  "猴子":"hóu zi","一块":"yī kuài","结果":"jié guǒ","高兴":"gāo xìng","掰开":"bāi kāi","扛着":"káng zhe",
  "往前":"wǎng qián","一棵":"yī kē","满足":"mǎn zú","扔掉":"rēng diào","摘花":"zhāi huā","手捧":"shǒu pěng",
  "追赶":"zhuī gǎn","来往":"lái wǎng","进去":"jìn qù",
  "牙刷":"yá shuā","毛巾":"máo jīn","擦手":"cā shǒu","梳子":"shū zi","梳头":"shū tóu","香皂":"xiāng zào",
  "洗澡":"xǐ zǎo","脸盆":"liǎn pén","洗脸":"xǐ liǎn","刷牙":"shuā yá","洗头":"xǐ tóu",
  // ===== 下册 · 第八单元 =====
  "棉花":"mián huā","姑娘":"gū niang","治病":"zhì bìng","她们":"tā men","燕子":"yàn zi","帮忙":"bāng máng",
  "别人":"bié rén","干活":"gàn huó","惊奇":"jīng qí","天空":"tiān kōng","才干":"cái gàn","身后":"shēn hòu",
  "火星":"huǒ xīng","多久":"duō jiǔ","卫星":"wèi xīng",
  "咕咚":"gū dōng","成熟":"chéng shú","掉下":"diào xià","湖面":"hú miàn","吓跑":"xià pǎo","啦啦队":"lā lā duì",
  "小鹿":"xiǎo lù","大象":"dà xiàng","野牛":"yě niú","拦着":"lán zhe","领路":"lǐng lù","哪里":"nǎ lǐ",
  "那些":"nà xiē","吓人":"xià rén","为什么":"wèi shén me","可怕":"kě pà","回家":"huí jiā","到来":"dào lái",
  "壁虎":"bì hǔ","借尾巴":"jiè wěi ba","困难":"kùn nan","爬走":"pá zǒu","您好":"nín hǎo","拨水":"bō shuǐ",
  "赶走":"gǎn zǒu","摆放":"bǎi fàng","过去":"guò qù","孩子":"hái zi","转身":"zhuǎn shēn","这边":"zhè biān",
  "赶快":"gǎn kuài","找人":"zhǎo rén","草地":"cǎo dì",
  "争吵":"zhēng chǎo","现在":"xiàn zài","头顶":"tóu dǐng","肥胖":"féi pàng","车票":"chē piào","户口":"hù kǒu",
  "上交":"shàng jiāo","父母":"fù mǔ","书页":"shū yè","义父":"yì fù"
};

